use_frameworks!

platform :ios, '8.0'

target 'KCNetworking_Example' do
  pod 'KCNetworking', :path => '../'

  target 'KCNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
